kind: Secret
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-admin_password: '{.data[''vnc_password'']}'
  labels:
    application: {{ .Values.name }}
    template: ubuntu-dev
  name: {{ .Values.name }}-secret
stringData:
  {{ if .Values.vnc_pw }}
    vnc-password: {{ .Values.vnc_pw | b64enc | quote }}
  {{ else }}
    vnc-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}         
type: Opaque
